### ISSUE TITLE
Investigate logo width on header

### ISSUE THREAD

**Issue by namanaman** [newjersey/njwds#51]
Currently, we have 
```css
// Header - prevent wrapping of logo text
.usa-header--extended {
  .usa-logo {
    max-width: 50%;
  }
}
```

This can lead to unexpected spacing on headers, such as between the logo and Menu button on the Innovation website (specifically mobile). We may want to look into removing this, adjusting the %, or adding a media query to only use it on desktop
